#### general settings
name: RealSR_NTIRE21
use_tb_logger: true
model: srgan
distortion: sr
scale: 4
gpu_ids: [2]

#### datasets
datasets:
  train:
    name: train
    mode: LQGT
    aug: ~
    noise_data: ../datasets/DF2K/Corrupted_noise/
    # dataroot_GT: /mnt/02520c27-ec8e-4661-b88f-05aa2011ffa7/ntire-sr-dataset/train
    dataroot_GT: ../datasets/DF2K/generated_kernel/tdsr/HR
    dataroot_LQ: ../datasets/DF2K/generated_kernel/tdsr/LR
    use_shuffle: true
    n_workers: 6  # per GPU
    batch_size: 16
    GT_size: 128
    use_flip: true
    use_rot: true
    color: RGB


### network structures
network_G:
  which_model_G: DWUNet
network_D:
 which_model_D: discriminator_vgg_128  # 修改GT_size时需要同时修改D的网络结构
 in_nc: 3
 nf: 64
 nlayer: 3

#### path
path:
  experiments_root: experiments/
  strict_load: true
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 1e-4
  weight_decay_G: 0
  beta1_G: 0.9
  beta2_G: 0.999
  lr_D: !!float 1e-4
  weight_decay_D: 0
  beta1_D: 0.9
  beta2_D: 0.999
  lr_scheme: MultiStepLR

  niter: 60001
  warmup_iter: -1  # no warm up
  # lr_steps: [5000, 20000, 30000, 50000, 80000, 150000]
  lr_steps: [5000, 20000, 30000, 40000]
  lr_gamma: 0.5

  pixel_criterion: l1         # edge_aware
  pixel_weight: !!float 1e-2  # 1
  feature_criterion: l1
  feature_weight: 1
  gan_type: ragan  # gan | ragan
  gan_weight: !!float 5e-3

  PS_init_iter: -1
  D_update_ratio: 1
  D_init_iters: 0

  manual_seed: 10
  val_freq: !!float 5e3

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
